config/routes.rb
Rails.application.routes.draw do

  root to: "lists#index"

  get "lists", to: "lists#index"
  get "lists/:id", to: "lists#show", as: :list

  # create new task, nested under lists
  resources :lists, only:[] do
    resources :tasks, only:[:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks.all
  end

  def new
  end

  def create
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list

  def new
    @task = Task.new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@list)
    end
  end

  private
  def set_list
    @list = List.find(params[:list_id])
  end
  def task_params
    params.require(:task).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
   <div class="title">
  <h1>My Lists</h1>
   </div>
  <div class="flex-container">
    <% @lists.each do |list| %>
      <div class="card">
        <p><%= link_to list.title, list_path(list) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="show-container">
  <div class="title-section">
    <h1 class="list-title"><%= @list.title %></h1>
  </div>

  <div class="tasks-section">
    <h2>Tasks</h2>
    <ul class="task-list">
      <% @tasks.each do |task| %>
        <li class="task-item"><%= task.title %></li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <div class="new-task">
      <%= link_to "Add a new task :)", new_list_task_path(@list), class: "btn btn-add-task" %>
    </div>
    <div class="overview-link">
      <%= link_to "Back to overview", lists_path, class: "btn btn-overview" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h2><%= @list.title %></h2>

<%= simple_form_for [@list, @task], html: { local: true} do |form| %>
    <%= form.input :title, label: "Task title" %>
  <div>
    <%= form.button :submit, "Create Task" %> 
  </div>
<% end %>

<div class="overview">
<%= link_to "Back to overview", lists_path %>
</div>